GetStream/stream-chat-java

src/main/java/io/getstream/chat/java/models/User.java
Currently image is required as a field (i.e. it cannot be null) for a User response. 
However, image is not a required field when creating a user (as per `UserRequestObject.builder()`).
All tests pass locally. For background, please see Zendesk ticket 13175
=> Allow a users image to be null.

src/main/java/io/getstream/chat/java/models/User.java, src/main/java/io/getstream/chat/java/services/framework/StreamServiceGenerator.java, src/test/java/io/getstream/chat/java/UserTest.java
Calling `createToken` throws an error: 
```
io.jsonwebtoken.security.WeakKeyException: The signing key's size is 72 bits which is not secure enough for the HS256 algorithm.  The JWT JWA Specification (RFC 7518, Section 3.2) states that keys used with HS256 MUST have a size >= 256 bits (the key size must be greater than or equal to the hash output size).  Consider using the io.jsonwebtoken.security.Keys class's 'secretKeyFor(SignatureAlgorithm.HS256)' method to create a key guaranteed to be secure enough for HS256.  See https://tools.ietf.org/html/rfc7518#section-3.2 for more information.
```
This should fix it by using the correct secret (not key). I've also added a test and set the subject/issuer.
=> fix: correct signing key is used

src/main/java/io/getstream/chat/java/models/Permission.java, src/test/java/io/getstream/chat/java/PermissionTest.java
This PR updates Permission.Condition type to `Map<String, Object>`. API change is not live yet
=> [CHAT-2260] Change Permission.Condition type

src/main/java/io/getstream/chat/java/models/Channel.java, src/main/java/io/getstream/chat/java/models/ChannelType.java, src/main/java/io/getstream/chat/java/services/ChannelService.java, src/test/java/io/getstream/chat/java/ChannelTest.java, src/test/java/io/getstream/chat/java/ChannelTypeTest.java
In order to fill up the code snippet examples in the [Permission V2 docs page](https://getstream.io/chat/docs/java/user_permissions/?preview=1&language=java), we need to be able to update grants on channel type level.
So basically this is support for ChannelType grants.
=> feat: add grants to channeltype

build.gradle, src/main/java/io/getstream/chat/java/models/Message.java, src/main/java/io/getstream/chat/java/models/User.java, src/main/java/io/getstream/chat/java/services/UserService.java, src/test/java/io/getstream/chat/java/MessageTest.java, src/test/java/io/getstream/chat/java/UserTest.java
- Full feature parity for Java
=> feat: add missing requests

.github/workflows/initiate_release.yml
The tags in this repository does not have v prefix. So it's not v1.5.0 but simply 1.5.0.
This is what this commit is fixing.
=> ci: fix initiate release job

README.md
Just made a fake commit to re-trigger release branch.
In this unnecessary commit, the badges are in a new line instead of being in the same line as the title.
=> ci: fake commit to retrigger release branch

src/main/java/io/getstream/chat/java/services/framework/DefaultClient.java
- Set connection pool lifetime from 5 minutes to 59 seconds
https://github.com/square/okhttp/blob/3ad1912f783e108b3d0ad2c4a5b1b89b827e4db9/okhttp/src/jvmMain/kotlin/okhttp3/ConnectionPool.kt#L36
=> feat: set pool lifetime to 59seconds

README.md
Basically, Lombok require Java9, but the generated code itself can run on Java8. So let's not confuse the customers here.
Also, I removed the last sentence, since I don't think we want to support non-LTS versions.
=> docs: update wording in the document

src/main/java/io/getstream/chat/java/models/App.java, src/main/java/io/getstream/chat/java/models/Channel.java, src/main/java/io/getstream/chat/java/models/Message.java, src/main/java/io/getstream/chat/java/services/MessageService.java
=> feat: added support for pending messages

src/main/java/io/getstream/chat/java/models/User.java
`created_by_id` is an optional field on deactivate user endpoint - https://getstream.io/chat/docs/python/update_users/?language=python#deactivate-a-user
=> fix: make created_by_id nullable in UserDeactivateRequest

src/test/java/io/getstream/chat/java/ChannelTest.java
This check the `notifications_muted` filter is working correctly for `queryMembers`
=> feat: add test for `notifications_muted` query members

publish.gradle
Gradle complained about tasks depending on each other.
https://github.com/GetStream/stream-chat-java/actions/runs/10416424942/job/28848632495
=> [PBE-5292] fix: ensure publish tasks run after sign tasks

src/main/java/io/getstream/chat/java/models/Channel.java, src/main/java/io/getstream/chat/java/services/ChannelService.java, src/test/java/io/getstream/chat/java/ChannelTest.java
=> [CHA-18] feat: member custom data, pinning and archiving

.github/workflows/ci.yml, src/main/java/io/getstream/chat/java/models/Flag.java, src/main/java/io/getstream/chat/java/models/Moderation.java, src/main/java/io/getstream/chat/java/models/UnreadCounts.java, src/main/java/io/getstream/chat/java/models/framework/StreamRequest.java, src/test/java/io/getstream/chat/java/ChannelTest.java
Add a few missing javadoc params.
=> fix: javadoc

src/test/java/io/getstream/chat/java/BasicTest.java, src/test/java/io/getstream/chat/java/ModerationTest.java
=> [CHA-0] Fix failing tests on CI

src/main/java/io/getstream/chat/java/models/ExportUsers.java, src/main/java/io/getstream/chat/java/services/ExportUsersService.java, src/test/java/io/getstream/chat/java/BasicTest.java, src/test/java/io/getstream/chat/java/ExportUsersTest.java
=> [CHA-710] feat: export users async task

src/main/java/io/getstream/chat/java/models/Draft.java, src/main/java/io/getstream/chat/java/services/DraftService.java, src/test/java/io/getstream/chat/java/ChannelDraftTest.java
=> [CHA-608] add draft endpoints

build.gradle, src/main/java/io/getstream/chat/java/models/Channel.java, src/main/java/io/getstream/chat/java/models/Message.java, src/main/java/io/getstream/chat/java/models/SharedLocation.java, src/main/java/io/getstream/chat/java/services/SharedLocationService.java, src/test/java/io/getstream/chat/java/SharedLocationTest.java
=> [CHA-649]: feature(CHA-769): add shared locations support

src/main/java/io/getstream/chat/java/models/App.java, src/test/java/io/getstream/chat/java/AppTest.java
We added support to configure a hook per product
- Add product field
- Add product constants
=> Add product scope hook config

src/test/java/io/getstream/chat/java/AppTest.java
- Fixed SQS and SNS hook creation by changing the id to UUID
- Fixed wrong event type input
- Convert pending message test to webhook v2
- Removed tests related to webhook v1
=> fix: Failing webhook tests

src/main/java/io/getstream/chat/java/models/App.java
Exposing `getEventHooks()` so it can be used to get the list of event hooks
=> fix: Expose getEventHooks()

src/main/java/io/getstream/chat/java/models/App.java
Change timeout_ms in event hooks to Number to match the old async moderation config
=> fix: Change timeout_ms in event hooks to Number to match the old config
