- .github/workflows/publish.yml
- .github/workflows/test.yml
- CONTRIBUTING.md
- README.md
- build.gradle
- src/test/java/io/getstream/chat/java/AppTest.java
- src/test/java/io/getstream/chat/java/BasicTest.java
- src/test/java/io/getstream/chat/java/BlocklistTest.java
- src/test/java/io/getstream/chat/java/ChannelTest.java
- src/test/java/io/getstream/chat/java/ChannelTypeTest.java
- src/test/java/io/getstream/chat/java/CommandTest.java
- src/test/java/io/getstream/chat/java/DeviceTest.java
- src/test/java/io/getstream/chat/java/EventTest.java
- src/test/java/io/getstream/chat/java/FlagTest.java
- src/test/java/io/getstream/chat/java/MessageTest.java
- src/test/java/io/getstream/chat/java/PermissionTest.java
- src/test/java/io/getstream/chat/java/ReactionTest.java
- src/test/java/io/getstream/chat/java/RoleTest.java
- src/test/java/io/getstream/chat/java/UserTest.java
> Add test action

- build.gradle
- src/main/java/io/getstream/chat/java/models/Message.java
- src/test/java/io/stream/BasicTest.java
- src/test/java/io/stream/MessageTest.java
> Feature: Search improvements

- README.md
Noticed a small error in the first simple example. Was missing a . before `.build()`
> FIxed minor typo in simple example

- src/main/java/io/getstream/chat/java/models/App.java
- src/main/java/io/getstream/chat/java/models/ChannelType.java
- src/main/java/io/getstream/chat/java/models/Message.java
- src/main/java/io/getstream/chat/java/models/Permission.java
- src/main/java/io/getstream/chat/java/models/Role.java
- src/main/java/io/getstream/chat/java/services/PermissionService.java
- src/main/java/io/getstream/chat/java/services/RoleService.java
- src/test/java/io/getstream/chat/java/PermissionTest.java
- src/test/java/io/getstream/chat/java/RoleTest.java
I've moved the Roles and Permissions to match the new Permissions V2 schema/endpoints. 
Updated message uploads to not `enrichResponse` since server headers are not returned for those endpoints.
> feat: Uplifted to PermissionsV2 schema.

- README.md
Updated the examples for how to create, update, remove and list custom permissions.
The role functions signatures have remained the same.
> chore: updated permissions v2 examples

- src/main/java/io/getstream/chat/java/models/App.java
> support asyncURLEnrichEnabled flag

- CHANGELOG.md
- build.gradle
> Release 1.3.3

- README.md
- src/main/java/io/getstream/chat/java/models/Channel.java
- src/main/java/io/getstream/chat/java/models/DeleteStrategy.java
- src/main/java/io/getstream/chat/java/models/TaskStatus.java
- src/main/java/io/getstream/chat/java/models/User.java
- src/main/java/io/getstream/chat/java/services/ChannelService.java
- src/main/java/io/getstream/chat/java/services/TaskStatusService.java
- src/main/java/io/getstream/chat/java/services/UserService.java
- src/test/java/io/getstream/chat/java/ChannelTest.java
- src/test/java/io/getstream/chat/java/TaskStatusTest.java
- src/test/java/io/getstream/chat/java/UserTest.java
Support background task operations
- Delete many users
- Delete many channels
- Soft/Hard strategies
- Task result
> Add batch async users/channels deletions

- CHANGELOG.md
- build.gradle
> Release 1.4.0

- .gitignore
- Makefile
- src/main/java/io/getstream/chat/java/models/Channel.java
- src/main/java/io/getstream/chat/java/services/ChannelService.java
- src/test/java/io/getstream/chat/java/ChannelTest.java
> feat: add options to truncate

- src/main/java/io/getstream/chat/java/models/App.java
- src/test/java/io/getstream/chat/java/BasicTest.java
- Extend app configs
- Fix failing tests. Apparently there are always 5 commands that stays.
> feat: extend app config

- .versionrc.js
Fix casing of build.gradle file. I hope this is the last PR. :facepalm:
> ci: fix casing of build.gradle file

- .github/CODEOWNERS
- src/main/java/io/getstream/chat/java/models/Channel.java
- src/test/java/io/getstream/chat/java/ChannelTest.java
> fix: channel custom fields

- src/main/java/io/getstream/chat/java/models/Flag.java
- src/main/java/io/getstream/chat/java/services/FlagService.java
- src/test/java/io/getstream/chat/java/FlagTest.java
> feat: add moderation apis

- src/main/java/io/getstream/chat/java/models/Channel.java
> feat: add commands to update

- src/main/java/io/getstream/chat/java/models/App.java
- src/main/java/io/getstream/chat/java/models/ChannelType.java
> feat: add reminders

- src/main/java/io/getstream/chat/java/models/App.java
- src/main/java/io/getstream/chat/java/services/AppService.java
> feat: add push provider

- src/main/java/io/getstream/chat/java/models/App.java
- src/main/java/io/getstream/chat/java/models/Device.java
- src/test/java/io/getstream/chat/java/DeviceTest.java
> feat: add provider fields

- src/main/java/io/getstream/chat/java/models/Channel.java
> feat(truncate): add truncated by id

- src/main/java/io/getstream/chat/java/models/App.java
> feat(app_settings): add offlineonly

- .github/workflows/ci.yml
- build.gradle
> ci: print test coverage

- src/main/java/io/getstream/chat/java/models/LanguageDeserializer.java
- src/main/java/io/getstream/chat/java/models/framework/StreamRequest.java
- src/test/java/io/getstream/chat/java/AppTest.java
- src/test/java/io/getstream/chat/java/UserTest.java
> fix: user language parsing

- src/main/java/io/getstream/chat/java/models/Language.java
Fixes #83 
Language model enum is not covered by tests, but should be self explanatory.
> fix: add "lt" to language model

- src/main/java/io/getstream/chat/java/models/Channel.java
> fix: null annotation of channel model

- build.gradle
- src/main/java/io/getstream/chat/java/services/framework/HttpLoggingInterceptor.java
Upgrade OkHttp Dependency to a newer version
> chore: use newer OkHttp dependency version

- src/main/java/io/getstream/chat/java/models/Message.java
- src/main/java/io/getstream/chat/java/services/MessageService.java
- src/test/java/io/getstream/chat/java/MessageTest.java
> feat: added `pending` property to message

- src/main/java/io/getstream/chat/java/models/Message.java
- src/test/java/io/getstream/chat/java/MessageTest.java
> [PBE-867] feat: added support for force_moderation on message

- .github/workflows/ci.yml
- src/main/java/io/getstream/chat/java/models/Message.java
- src/test/java/io/getstream/chat/java/BasicTest.java
- src/test/java/io/getstream/chat/java/MessageTest.java
> add new field to Message

- src/main/java/io/getstream/chat/java/models/ChannelType.java
> [PBE-0] - Adding quotes to channel type

- src/main/java/io/getstream/chat/java/models/ChannelType.java
- src/test/java/io/getstream/chat/java/ChannelTypeTest.java
> [PBE-0] fix: quotes

- src/main/java/io/getstream/chat/java/models/Message.java
- src/test/java/io/getstream/chat/java/MessageTest.java
> feat: allow search with offset and sort

- src/main/java/io/getstream/chat/java/models/Message.java
- src/main/java/io/getstream/chat/java/services/MessageService.java
- src/test/java/io/getstream/chat/java/MessageTest.java
> feat: support message unblock endpoint

- src/main/java/io/getstream/chat/java/models/Channel.java
- src/test/java/io/getstream/chat/java/ChannelTest.java
> [PBE-1063] allow sending invites when creating a channel

- src/main/java/io/getstream/chat/java/models/Message.java
- src/test/java/io/getstream/chat/java/MessageTest.java
> feat: add the ability to set message type when sending a message

- build.gradle
> remove unused dependency

- src/main/java/io/getstream/chat/java/models/UnreadCounts.java
- src/main/java/io/getstream/chat/java/services/UnreadCountsService.java
- src/test/java/io/getstream/chat/java/UnreadCountsTest.java
This PR implements unread counts API including the batch version.
> feat: unread counts

- src/main/java/io/getstream/chat/java/models/User.java
- src/test/java/io/getstream/chat/java/UserTest.java
Adds the ability to query deactivated users.
> feat: query deactivated users

- src/main/java/io/getstream/chat/java/models/Channel.java
- src/test/java/io/getstream/chat/java/ChannelTest.java
Adds `notifications_muted` field to `ChannelMember` type.
> feat: add the new property

- build.gradle
> fix: update dependency for security. fixes #138

- src/main/java/io/getstream/chat/java/models/MessageHistory.java
- src/main/java/io/getstream/chat/java/services/MessageHistoryService.java
- src/test/java/io/getstream/chat/java/MessageHistoryTest.java
> feat: add message history api

- src/main/java/io/getstream/chat/java/models/Import.java
- src/test/java/io/getstream/chat/java/ImportTests.java
> [PBE-0] fix: request param name file_name -> filename

- .github/workflows/release.yml
`publishReleasePublicationToSonatypeRepository` only published the `release` publication.
> [PBE-5292] feat: publish the shadow publication as well

- publish.gradle
Sonatype repo complained about missing javadoc and sources jars. Also about some missing info in the pom file.
> [PBE-5292] Fix shadow publication

- README.md
Updates readme to include the information about the shadowed version. Also formats the readme file.
> [PBE-5292] fix: update the readme to include the shadowed version

- src/main/java/io/getstream/chat/java/services/framework/DefaultClient.java
Instead of rereading version properties file client now reads version into static property and use it.
> Fix version reread

- src/main/java/io/getstream/chat/java/models/Channel.java
> fix: add missing enum value

- src/main/java/io/getstream/chat/java/models/App.java
- src/test/java/io/getstream/chat/java/AppTest.java
Adds the missing field `sizeLimit` to `FileUploadConfig`.
> fix: add missing field

- src/main/java/io/getstream/chat/java/models/Message.java
- src/test/java/io/getstream/chat/java/MessageTest.java
This PR introduces a restricted visibility feature
> Added restricted visibility

- DOCS.md
- src/main/java/io/getstream/chat/java/models/Message.java
- src/main/java/io/getstream/chat/java/services/MessageService.java
- src/test/java/io/getstream/chat/java/MessageTest.java
> feat(server): added deleted by filed

- src/main/java/io/getstream/chat/java/models/App.java
- src/test/java/io/getstream/chat/java/AppTest.java
We are introducing multi-event hooks where customer can configure multiple hook targets for events. We added `EventHooks` to  `App` class.
> Add EventHooks field to App

- src/main/java/io/getstream/chat/java/models/ChannelType.java
> feat: [CHA-1300] add count messages to channel type
